### ISSUE TITLE
Mark the repo as a template

### ISSUE THREAD

**Issue by melosh101** [Darkhax/Minecraft-Modding-Template#2]
Hey
i thought marking this repo as a template would make a lot of sense.
it would allow users to quickly create a new repo without forking this one or having to mess with remotes.
it can be changed in the repo settings in the checkbox called "Template repository"

Love the hard work you guys have put into this repo

**Comment by Darkhax** [comment]
Thanks, this repo is primarily intended for my own use or as an example for other authors. It probably shouldn't be cloned directly unless you're pretty familiar with Gradle, modding, and how I manage my own projects. 

If you are interested in the multiple loader functionality you should refer to [this repo](https://github.com/jaredlll08/MultiLoader-Template) which is an actual template.
